Blog/urls.py
from django.urls import path
from Blog.views import (
    inicio,
    about,
)
from django.views.generic.base import TemplateView


from Blog.class_views import (
    BlogListView,
    BlogCreateView,
    BlogDetailView,
    BlogDeleteView,
    BlogUpdateView,
)


urlpatterns = [
    path("", TemplateView.as_view(template_name="Blog/index.html"), name="Inicio"),
    path("pages/", BlogListView.as_view(), name="Pages"),
    path("about/", about, name="Acerca De"),
    path(
        "new-blog/",
        BlogCreateView.as_view(),
        name="Nuevo Blog",
    ),
    path("blog-detail/<int:pk>/", BlogDetailView.as_view(), name="Blog Detail"),
    path(
        "blog-delete/<int:pk>/",
        BlogDeleteView.as_view(),
        name="Blog Delete",
    ),
    path(
        "blog-update/<int:pk>/",
        BlogUpdateView.as_view(),
        name="Blog Update",
    ),
]

ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("Blog.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("Users.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from Users.views import login_request, register, edit, profile

app_name = "Users"


urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
        ),
        name="Login",
    ),
    path("register/", register, name="Register"),
    path("profile/", profile, name="Profile"),
    path(
        "logout/", LogoutView.as_view(template_name="users/logout.html"), name="Logout"
    ),
    path("edit/", edit, name="Edit"),
]

Blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(
        max_length=150,
    )
    subtitle = models.CharField(max_length=150, null=True)
    body = models.CharField(max_length=150, null=True)
    author = models.CharField(max_length=150, null=True)
    date = models.DateField(
        blank=True,
        null=True,
    )
    image = models.ImageField(upload_to="blog_images/", blank=True, null=True)

Users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.


class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    imagen = models.ImageField(upload_to="avatars", null=True, blank=True)

    def __str__(self):
        return f"{settings.MEDIA_URL}{self.imagen}"

Blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class FormularioRedactor(forms.Form):
    nombre = forms.CharField(max_length=20)
    email = forms.CharField(max_length=30)
    edad = forms.IntegerField()


class FormularioComentador(forms.Form):
    nombre = forms.CharField(max_length=20)
    email = forms.CharField(max_length=30)
    edad = forms.IntegerField()


class FormularioModerador(forms.Form):
    nombre = forms.CharField(max_length=20)
    email = forms.CharField(max_length=30)


class Buscar(forms.Form):
    nombre = forms.CharField()

Users/forms.py
from django import forms

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Ingrese su email")
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    username = forms.CharField(required=False)
    imagen = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2", "imagen"]
        help_texts = {k: "" for k in fields}


class UserEditForm(UserCreationForm):
    email = forms.EmailField(label="Ingrese su email", required=False)
    password1 = forms.CharField(
        label="Contraseña", widget=forms.PasswordInput, required=False
    )
    password2 = forms.CharField(
        label="Repetir contraseña", widget=forms.PasswordInput, required=False
    )

    username = forms.CharField(required=False)

    imagen = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2", "imagen"]

Blog/views.py
from django.shortcuts import render

# Create your views here.


def inicio(request):
    return render(request, "Blog/index.html")


def pages(request):
    return render(request, "Blog/pages.html")


def about(request):
    return render(request, "Blog/about.html")

Users/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from Users.forms import UserRegisterForm, UserEditForm
from Users.models import Avatar
from django.contrib.auth import update_session_auth_hash


# Create your views here.


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            usuario = form.cleaned_data.get("username")

            clave = form.cleaned_data.get("password")

            nombre_usuario = authenticate(request, username=usuario, password=clave)

            if usuario is not None:
                login(request, nombre_usuario)

                return render(
                    request,
                    "Blog/index.html",
                    {"name": usuario, "mensaje": f" Has iniciado sesión"},
                )

        else:
            return render(
                request,
                "Blog/index.html",
                {"mensaje": "Error, datos incorrectos"},
            )

    form = AuthenticationForm()

    return render(request, "Users/login.html", {"form": form})


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            update_session_auth_hash(request, request.user)
            return render(
                request,
                "Blog/index.html",
                {"mensaje": f"El nuevo usuario '{username}' ha sido creado"},
            )
    else:
        form = UserRegisterForm()

    return render(request, "users/register.html", {"form": form})


@login_required
def edit(request):
    user = request.user
    if request.method == "POST":
        form = UserEditForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data

            if data["password1"] != data["password2"]:
                data = {
                    "username": user.username,
                    "email": user.email,
                    "password1": user.password,
                }
                form = UserEditForm(initial=data)

            else:
                user.email = data["email"]
                user.username = data["username"]
                user.set_password(data["password1"])
                user.save()

                update_session_auth_hash(request, request.user)

                try:
                    avatar = Avatar.objects.get(user=user)

                except Avatar.DoesNotExist:
                    avatar = Avatar(user=user, imagen=data["imagen"])
                    avatar.save()
                else:
                    avatar.imagen = data["imagen"]
                    avatar.save()
                    update_session_auth_hash(request, request.user)

                return render(request, "Blog/index.html")

    else:
        form = UserEditForm(initial={"username": user.username, "email": user.email})

    return render(request, "Users/edit.html", {"form": form, "usuario": user.username})


@login_required
def profile(request):
    user = request.user
    return render(request, "Users/profile.html", {"user": user})

Blog/templates/Blog/about.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Acerca de
mí {% endblock pageName %} {% block dynamic_content %}

<header class="masthead">
  <div class="container">
    <div class="masthead-heading text-uppercase">ACERCA DE</div>
  </div>
</header>

<section class="page-section bg-light" id="team">
  <div class="container">
  
    <div class="row">
      <div class="col-lg-4 mx-auto">
        <div class="team-member">
          <img
            class="rounded-circle"
            src="{% static 'Blog/assets/img/profile.jpg' %}"
            alt="..."
          />
          <h4>Sebastian Lopez Lindoro</h4>
          <p class="text-muted">Estudiante</p>
          <a
            class="btn btn-dark btn-social mx-2"
            href="https://twitter.com/?lang=es"
            aria-label="Diana Petersen Twitter Profile"
            target="_blank"
            
            ><i class="fab fa-twitter"></i
          ></a>
          <a
            class="btn btn-dark btn-social mx-2"
            href="https://www.facebook.com/?locale=es_LA"
            aria-label="Diana Petersen Facebook Profile"
            target="_blank"
            ><i class="fab fa-facebook-f"></i
          ></a>
          <a
            class="btn btn-dark btn-social mx-2"
            href="https://ar.linkedin.com/"
            aria-label="Diana Petersen LinkedIn Profile"
            target="_blank"
            ><i class="fab fa-linkedin-in"></i
          ></a>
        </div>
      </div>
    
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <p class="large text-muted">
          Blog proyecto final curso de Python en Coderhouse comision 47780 ¡Gracias por la visita!
        </p>
      </div>
    </div>
  </div>
</section>
{% endblock dynamic_content %}

Blog/templates/Blog/blog_confirm_delete.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %}
Confirmación de eliminado {% endblock pageName %} {% block dynamic_content %}

<header class="masthead">
  <div class="container">
    <div class="masthead-heading text-uppercase">ELIMINAR BLOG</div>
  </div>
</header>

<form action="" method="POST">
  {% csrf_token %}
  <h5
    style="margin-top: 50px"
    class="text-uppercase justify-content-center text-center"
  >
    ¿Quieres eliminar el blog seleccionado?
  </h5>
  <!-- Submit Button-->
  <div class="text-center">
    <input
      class="btn btn-primary btn-xl text-uppercase"
      type="submit"
      value="Eliminar Blog"
      style="margin-top: 40px"
    />
  </div>
  <div class="text-center">
    <div style="margin-top: 50px" class="text-center">
      <a
        class="btn btn-primary btn-xl text-uppercase text-center justify-content-center"
        href="{% url 'Pages' %}"
      >
        Volver
      </a>

  </div>
</form>
{% endblock dynamic_content %}


</div>

Blog/templates/Blog/blog_detail.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Detalle
del blog {% endblock pageName %} {% block dynamic_content %}

<header class="masthead">
  <div class="container">
    <div class="masthead-heading text-uppercase">DETALLE DEL BLOG</div>
  </div>
</header>

<div class="modal-dialog">
  <div class="modal-content justify-content-center">
    <div class="container justify-content-center">
      <div class="row justify-content-center">
        <div class="col-lg-8 justify-content-center">
          <div class="modal-body justify-content-center">
            <!-- Project details-->
            <h2
              style="margin-top: 50px"
              class="text-uppercase justify-content-center text-center"
            >
              {{blog.title}}
            </h2>
            <h5
              style="margin-top: 40px"
              class="item-intro text-muted text-center"
            >
              {{blog.subtitle}}
            </h5>
            <h6
              style="margin-top: 40px"
              class="item-intro text-muted text-center"
            >
              Escrito por {{blog.author}}
            </h6>

            <p
              style="margin-top: 40px"
              class="item-intro text-muted text-center"
            >
              {{blog.date}}
            </p>
            <img
              class="img-fluid d-block mx-auto"
              src="/media/{{blog.image}}"
              alt="..."
            />
            <p
              style="margin-top: 40px"
              class="justify-content-center text-center"
            >
              {{blog.body}}
            </p>
            <div style="margin-top: 50px" class="text-center">
              <a
                class="btn btn-primary btn-xl text-uppercase text-center justify-content-center"
                href="{% url 'Pages' %}"
              >
                Ver todos los blogs
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock dynamic_content %}

Blog/templates/Blog/blog_edit.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Editar
Blog {% endblock pageName %} {% block dynamic_content %}

<section class="page-section" id="contact">
  <div class="container">
    <div class="text-center">
      <h2 class="section-heading text-uppercase">EDITAR BLOG</h2>
      <h3 class="section-subheading text-muted"></h3>
    </div>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- ACA EMPIEZA EL FORM-->
      <div class="row mb-5 text-center" style="justify-content: center">
        <div class="col-md-6 text-center">
          <p>
            <label style="color: white" for="id_title">Titulo:</label>
            <input
              class="form-control"
              type="text"
              name="title"
              value="{{blog.title}}"
              maxlength="150"
              required
              id="id_title"
            />
          </p>

          <p>
            <label style="color: white" for="id_subtitle">Subtítulo:</label>
            <input
              class="form-control"
              type="text"
              name="subtitle"
              value="{{blog.subtitle}}"
              maxlength="150"
              required
              id="id_subtitle"
            />
          </p>

          <p>
            <label style="color: white" for="id_body">Cuerpo:</label>
            <input
              class="form-control"
              type="text"
              name="body"
              value="{{blog.body}}"
              maxlength="150"
              required
              id="id_body"
            />
          </p>

          <p>
            <label style="color: white" for="id_author">Autor:</label>
            <input
              class="form-control"
              type="text"
              name="author"
              value="{{blog.author}}"
              maxlength="150"
              required
              id="id_author"
            />
          </p>

          <p>
            <label style="color: white" for="id_date">Fecha:</label>
            <input
              class="form-control"
              type="date"
              name="date"
              value="{{ request.user.date_joined |date:'Y M D' }}"
              required
              id="id_date"
            />
          </p>

          {% if user.is_superuser %}

          <p>
            <label style="color: white" for="id_image">Image:</label>

            <a
              style="margin-bottom: 20px"
              href="/media/blog_images/wallpaperflare.com_wallpaper_cswhnEe.jpg"
              >blog_images/wallpaperflare.com_wallpaper_cswhnEe.jpg</a
            >

            Change:
            <input
              type="file"
              name="image"
              accept="image/*"
              id="id_image"
              class="text-center justify-content-center"
              style="margin-bottom: 20px"
            />
          </p>

          {% else %}

          <p style="margin-top: 35px" class="section-heading text-uppercase">
            Para editar las imágenes debes ser un administrador
          </p>

          {% endif %}

          <!-- ACA TERMINA EL FORM-->

          <input
            style="margin-top: 20px"
            class="btn btn-primary btn-l text-uppercase text-center justify-content-center"
            type="submit"
            value="Editar Blog"
          />
        </div>
      </div>
    </form>

    {% endblock dynamic_content %}
  </div>
</section>

Blog/templates/Blog/index.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Homepage
{% endblock pageName %} {% block dynamic_content %}

<header class="masthead">
  <div class="container">
    <div class="masthead-subheading">¡Bienvenido a nuestro blog!</div>
    <div class="masthead-heading text-uppercase">Nos encanta tenerte aquí</div>
    <a class="btn btn-primary btn-xl text-uppercase" href="{% url 'Pages' %}"
      >Últimos Blogs</a
    >
    <div style="margin-top: 60px" class="masthead-subheading">{{mensaje}}</div>
  </div>
</header>

{% endblock dynamic_content %}

Blog/templates/Blog/new_blog.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Nuevo Blog
{% endblock pageName %} {% block dynamic_content %}

<section class="page-section" id="contact">
  <div class="container">
    <div class="text-center">
      <h2 class="section-heading text-uppercase">CREA UN NUEVO BLOG</h2>
      <h3 class="section-subheading text-muted"></h3>
    </div>
    

    <form
      id="contactForm"
      data-sb-form-api-token="API_TOKEN"
      action=""
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}

      <div class="row mb-5 text-center" style="justify-content: center">
        <div class="col-md-6 text-center">
          <div class="form-group text-center">
        
            <input
              class="form-control"
              id="title"
              type="text"
              placeholder="Título"
              data-sb-validations="required"
              name="title"
            />
            <div class="invalid-feedback" data-sb-feedback="name:required">
              Ingrese un título válido
            </div>
          </div>
          <div class="form-group text-center">
            
            <input
              class="form-control"
              id="subtitle"
              type="text"
              placeholder="Subtítulo"
              data-sb-validations="required"
              name="subtitle"
            />
            <div class="invalid-feedback" data-sb-feedback="name:required">
              Ingrese un subtítulo válido
            </div>
          </div>
          <div class="form-group text-center">
           
            <input
              class="form-control"
              id="body"
              type="text"
              placeholder="Cuerpo"
              data-sb-validations="required"
              name="body"
            />
            <div class="invalid-feedback" data-sb-feedback="name:required">
              Ingrese un cuerpo válido
            </div>
          </div>
            <div class="form-group text-center">
             
              <input
                class="form-control"
                id="author"
                type="text"
                placeholder="Autor"
                data-sb-validations="required"
                name="author"
              />
              <div class="invalid-feedback" data-sb-feedback="name:required">
                Ingrese un autor válido
              </div>
            </div>
            <div class="form-group">
             
              <input
                class="form-control"
                id="date"
                type="date"
                placeholder="Date"
                data-sb-validations="required"
                name="date"
              />
              <div class="invalid-feedback" data-sb-feedback="email:required">
                Ingrese una fecha válida
              </div>
            </div>
            <div class="form-group mb-md-0">
          
              
              <input
                class="form-control hidden"
                id="image"
                type="file"
                placeholder="Imagen"
                data-sb-validations="required"
                name="image"
                
              />
              <div class="invalid-feedback" data-sb-feedback="phone:required">
                Suba una imagen válida
              </div>
            </div>
          </div>
        </div>
        <!-- Submit Button-->
        <div class="text-center">
          <input
            class="btn btn-primary btn-xl text-uppercase"
            type="submit"
            value="Crear Blog"
          />
        </div>
      </div>
    </form>
  </div>
</section>

{% endblock dynamic_content %} 

Blog/templates/Blog/pages.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Listado de
blogs {% endblock pageName %} {% block dynamic_content %}

<header class="masthead">
  <div class="container">
    <div class="masthead-heading text-uppercase">Listado de blogs</div>
  </div>
</header>

<section class="page-section" id="services">
  <div class="container">
    <div class="row text-center">
      {% if not object_list %}

      <h3 class="section-heading text-uppercase">
        No se han encontrado blogs disponibles
      </h3>
      <br />
      <br />
      <br />

      {% else %} {% for blog in object_list %}

      <div class="col-lg-4">
        <div class="team-member">
          <img
            class="mx-auto rounded-circle"
            src="/media/{{ blog.image }}"
            alt="..."
          />

          <h4 class="my-3">{{blog.title}}</h4>
          <p class="text-muted">
            {{blog.author}} <br />
            {{blog.date}}
          </p>
          <a
            class="btn btn-dark mx-2"
            href="{% url 'Blog Detail' blog.id %}"
            aria-label="Parveen Anand Twitter Profile"
          >
            Leer más</a
          >
          <a
            class="btn btn-dark mx-2"
            href="{% url 'Blog Update' blog.id %}"
            aria-label="Parveen Anand Twitter Profile"
          >
            Editar</a
          >
          <a
            class="btn btn-dark mx-2"
            href="{% url 'Blog Delete' blog.id %}"
            aria-label="Parveen Anand Twitter Profile"
          >
            Eliminar</a
          >
        </div>
      </div>

      {% endfor %} {% endif %}

      <div class="team-member">
        <a
          class="btn btn-dark mx-2"
          href="{% url 'Nuevo Blog' %}"
          aria-label="Parveen Anand Twitter Profile"
          style="margin-top: 60px"
        >
          CREA UN NUEVO BLOG</a
        >
      </div>
    </div>
  </div>
</section>

{% endblock dynamic_content %}

Users/templates/Users/edit.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Crear nuevo usuario {% endblock pageName %} {% block dynamic_content %}


<section class="page-section" id="contact">
  <div class="container">
    <div class="text-center">
      <h2 class="section-heading text-uppercase">EDITAR USUARIO</h2>
      <h3 class="section-subheading text-muted"></h3>
    </div>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}  
      <div class="row mb-5 text-center" style="justify-content: center">
        <div class="col-md-6 text-center">
          <div class="form-group text-center">
        
      <p>
        <label style="color: white;" for="id_username">Username:</label>
        <input class="form-control" type="text" value="{{user.username}}" name="username" autofocus id="id_username">
        
        
      </p>
    
      
      <p>
        <label style="color: white;" for="id_email">Email:</label>
        <input class="form-control" type="email" name="email" value="{{user.email}}" maxlength="320" id="id_email">
        
        
      </p>
    
      <p>
        <label style="color: white;" for="id_username">Contraseña:</label>
        <input class="form-control" type="password"  name="password1" autofocus id="id_username">
        
        
      </p>
    
      <p>
        <label style="color: white;" for="id_username">Repita su contraseña:</label>
        <input class="form-control" type="password"  name="password2" autofocus id="id_username">
        
        
      </p>
    
      
      <p>
        <label style="color: white;" for="id_imagen">Imagen:</label>
        <input class="form-control" type="file" name="imagen" accept="image/*" id="id_imagen">
        
        
      </div>
    </div>
  </div>
      <div class="text-center">
        <input
          class="btn btn-primary btn-xl text-uppercase"
          type="submit"
          value="Editar"
        />
      </div>
      
    {% endblock dynamic_content %}
  </div>
</section>

Users/templates/Users/login.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Iniciar sesión {% endblock pageName %} {% block dynamic_content %}


<section class="page-section" id="contact">
  <div class="container">
    <div class="text-center">
      <h2 class="section-heading text-uppercase">INICIAR SESIÓN</h2>
      <h3 class="section-subheading text-muted"></h3>
    </div>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}  
      
      <div class="row mb-5 text-center" style="justify-content: center">
        <div class="col-md-6 text-center">
          <div class="form-group text-center">
        
            <input
              class="form-control"
              id="title"
              type="text"
              placeholder="Nombre de usuario"
              data-sb-validations="required"
              name="username"
              autocomplete="username"
            />
            <div class="invalid-feedback" data-sb-feedback="name:required">
              Ingrese un nombre de usuario válido
            </div>
          </div>
          <div class="form-group text-center">
            
            <input
              class="form-control"
              id="subtitle"
              type="password"
              placeholder="Contraseña"
              data-sb-validations="required"
              name="password"
              autocomplete="current-password"
              style="margin-top: 20px;"
            />
            <div class="invalid-feedback" data-sb-feedback="name:required">
              Ingrese un subtítulo válido
            </div>
          </div>
        </div>
      </div>

      <div class="text-center">
        <input
          class="btn btn-primary btn-xl text-uppercase"
          type="submit"
          value="Iniciar sesión"
        />
      </div>
      <!-- ACA EMPIEZA EL FORM-->
    {% endblock dynamic_content %}
  </div>
</section>




<!-- <p>
  <label for="id_username">Username:</label>
  <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
  
  
</p>


<p>
  <label for="id_password">Password:</label>
  <input type="password" name="password" autocomplete="current-password" required id="id_password"> -->


  
  <!-- ACA EMPIEZA EL FORM-->
    
  

Users/templates/Users/logout.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Iniciar
sesión {% endblock pageName %} {% block dynamic_content %}

<header class="masthead">
  <div class="container">
    <div class="masthead-subheading">Te has deslogueado</div>
    <a class="btn btn-primary btn-xl text-uppercase" href="{% url 'Inicio' %}"
      >Volver al inicio</a
    >
  </div>
</header>

{% endblock dynamic_content %}

Users/templates/Users/profile.html
{% extends "Blog/main.html" %} {% load static %} {% block pageName %} Tu Perfil {% endblock pageName %} {% block dynamic_content %}

<header class="masthead">
  <div class="container">
    <div class="masthead-heading text-uppercase">TU PERFIL</div>
  </div>
</header>

<section class="page-section bg-light" id="team">
  <div class="container">
  
    <div class="row">
      <div class="col-lg-4 mx-auto">
        <div class="team-member">
          <img
            class="mx-auto rounded-circle"
            src="{{user.avatar}}"
          />
          <h4>{{user.username}}</h4>
          <p class="text-muted">{{user.email}}</p>
      
        </div>
      </div>
   
      <div class="container text-center justify-content-center">
        
        <a class="btn btn-primary btn-l text-uppercase " href="{% url 'Users:Edit' %}"
          >Editar Perfil</a
        >
      </div>
  </div>
</section>
{% endblock dynamic_content %}